#!/usr/bin/env bash
set -e

export LOG_FILE=/tmp/install.log
rm -f $LOG_FILE
touch $LOG_FILE
chmod 666 $LOG_FILE

echo -e "\nStarting \033[1mlamassu-server\033[0m install. This will take a few minutes...\n"

if [ "$(whoami)" != "root" ]; then
  echo -e "This script has to be run as \033[1mroot\033[0m user"
  exit 3
fi

cd ~

export IP=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')

echo "Updating system..."
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - >> $LOG_FILE 2>&1
add-apt-repository -y ppa:bitcoin/bitcoin >> $LOG_FILE 2>&1
add-apt-repository -y ppa:ethereum/ethereum >> $LOG_FILE 2>&1
apt-get update -q >> $LOG_FILE 2>&1

echo "Installing necessary packages..."
apt-get install nodejs python-minimal ethereum bitcoind build-essential postgresql libpq-dev -y -q >> $LOG_FILE 2>&1
npm install node-hkdf-sync >> $LOG_FILE 2>&1

echo "Creating lamassu user..."
useradd -m lamassu >> $LOG_FILE 2>&1

SEEDS_DIR=~lamassu/seeds
export SEED_FILE=$SEEDS_DIR/seed.txt
mkdir -p $SEEDS_DIR >> $LOG_FILE 2>&1
chown lamassu $SEEDS_DIR >> $LOG_FILE 2>&1

echo "Generating seed..."
export SEED=$(openssl rand -hex 32)
echo $SEED > $SEED_FILE

SALT="lamassu-server-salt"
HKDF_SCRIPT="const HKDF = require('node-hkdf-sync'); \
const seed = new Buffer('$SEED', 'hex'); \
const hkdf = new HKDF('sha256', '$SALT', seed); \
console.log(hkdf.derive('postgres-pw', 32).toString('hex'))"

export POSTGRES_PW=$(node -e "$HKDF_SCRIPT")

echo "Creating postgres user..."
su -l postgres >> $LOG_FILE 2>&1 <<EOF
  psql -c "CREATE ROLE lamassu_pg WITH LOGIN SUPERUSER PASSWORD '$POSTGRES_PW';"
  createdb lamassu
EOF

echo "Setting up backups..."
BACKUP_DIR=/opt/backups/postgresql
mkdir -p $BACKUP_DIR
chown root:postgres $BACKUP_DIR >> $LOG_FILE 2>&1
chmod 664 $BACKUP_DIR >> $LOG_FILE 2>&1
BACKUP_CRON="@daily $BIN/backup-pg > /dev/null"
echo $BACKUP_CRON | crontab -u postgres - >> $LOG_FILE 2>&1

echo "Setting up firewall..."
ufw allow ssh >> $LOG_FILE 2>&1
ufw allow 8081/tcp >> $LOG_FILE 2>&1  # Admin
ufw allow 3000/tcp >> $LOG_FILE 2>&1  # Server
ufw -f enable >> $LOG_FILE 2>&1

cd ~lamassu
cp /vagrant/install-lamassu.sh .  # FIX to download
chown lamassu ./install-lamassu.sh >> $LOG_FILE 2>&1
chmod 755 ./install-lamassu.sh >> $LOG_FILE 2>&1
su lamassu -c ./install-lamassu.sh
cd ~

BIN=$(su lamassu -c "npm bin")
export PATH=$PATH:$BIN
echo "export PATH=\$PATH:$BIN" >> $HOME/.profile
