#!/usr/bin/env bash
set -e

LOG_FILE=/tmp/install.log

rm -f $LOG_FILE

echo -e "\nStarting \033[1mlamassu-server\033[0m install. It will take a few minutes...\n"

echo "Updating system..."
add-apt-repository -y ppa:bitcoin/bitcoin >> $LOG_FILE 2>&1
add-apt-repository -y ppa:ethereum/ethereum >> $LOG_FILE 2>&1
apt-get update -q >> $LOG_FILE 2>&1

echo "Installing necessary packages..."
apt-get install npm python-minimal ethereum bitcoind build-essential postgresql -y -q >> $LOG_FILE 2>&1

echo "Installing n..."
npm install -g n >> $LOG_FILE 2>&1

echo "Upgrading nodejs..."
n lts >> $LOG_FILE 2>&1

echo "Installing postgresql..."
mkdir -p /opt/apps/node_modules
mkdir -p /opt/apps/seeds
cd /opt/apps

echo "Installing lamassu-server..."
npm install npm install lamassu/lamassu-server#two-way-db-changes lamassu-scripts >> $LOG_FILE 2>&1
npm install bunyan pm2 -g >> $LOG_FILE 2>&1
pm2-logrotate >> $LOG_FILE 2>&1
BIN=$(npm bin)
echo "Creating DB..."
SEED=$(openssl rand -hex 32)
echo $SEED > /opt/apps/seeds/seed.txt

echo "Upgrading db schema..."
POSTGRES_PW=$($BIN/hkdf postgres-pw $SEED)
ADMIN_PW=$($BIN/hkdf lamassu-admin-pw $SEED)
su - postgres >> $LOG_FILE 2>&1 <<EOF
  psql -c "CREATE ROLE lamassu WITH LOGIN SUPERUSER PASSWORD '$POSTGRES_PW';"
  createdb lamassu
EOF
cd node_modules/lamassu-server
$BIN/migrate >> $LOG_FILE 2>&1

echo "Installing lamassu-admin..."
cd ../..
npm install lamassu-admin >> $LOG_FILE 2>&1
$BIN/lamassu-useradd admin $ADMIN_PW

echo "Generating SSL certificates..."
ip=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
openssl req -new -newkey rsa:4096 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$ip:8081" -keyout /root/lamassu-admin.key  -out /root/lamassu-admin.crt >> $LOG_FILE 2>&1
openssl req -new -newkey rsa:4096 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$ip:3000" -keyout /root/lamassu-server.key -out /root/lamassu-server.crt >> $LOG_FILE 2>&1

cat <<EOF > /etc/lamassu.json
{
  "postgresql": "postgres://lamassu:$POSTGRES_PW@localhost/lamassu",
  "certPath": "/root/lamassu-server.key",
  "certKey": "/root/lamassu-server.key"
}
EOF

echo "Starting servers..."
pm2 start $BIN/lamassu-server
pm2 start $BIN/lamassu-admin

pm2 startup >> $LOG_FILE 2>&1

echo
echo "Done! Now it's time to configure Lamassu stack."
echo "Open https://$ip:8081 in your browser to access "
echo "your admin panel."
echo
echo "Default login info for lamassu-admin:"
echo "User: admin / Password: $ADMIN_PW"
echo
echo "Please write this down in a safe place."
echo -e "\n*** IMPORTANT ***"
echo "Backup the contents of /opt/apps/seeds/seed.txt in a safe place."
echo "This seed will allow you to retrieve system passwords, including your db password"
echo "and they keys to your Ethereum accounts."
