#!/usr/bin/env bash
set -e

LOG_FILE=/tmp/install.log

echo -e "\nStarting \033[1mlamassu-server\033[0m install, this will take a few minutes...\n"
echo "Updating system..."
apt-get update -q >> $LOG_FILE 2>&1
echo "Installing nodejs and python..."
apt-get install nodejs-legacy python-minimal build-essential -y -q >> $LOG_FILE 2>&1
echo "Installing n..."
npm install -g n >> $LOG_FILE 2>&1
echo "Upgrading nodejs..."
n lts >> $LOG_FILE 2>&1
echo "Installing postgresql..."
apt-get install postgresql -y -q >> $LOG_FILE 2>&1
echo "Creating DB..."
password=$(openssl rand -hex 32)
echo "{\"postgresql\":\"postgres://lamassu:$password@localhost/lamassu\"}" > /etc/lamassu.json
su - postgres >> $LOG_FILE 2>&1 <<EOF
  psql -c "CREATE ROLE lamassu-pg WITH LOGIN SUPERUSER PASSWORD '$password';"
  createdb lamassu
EOF
echo "Installing lamassu-server..."
mkdir -p /opt/apps/node_modules
cd /opt/apps
npm install lamassu-server@beta
echo "Generating SSL certificates..."
openssl req -new -newkey rsa:4096 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$ip:8081" -keyout /root/lamassu-admin.key  -out /root/lamassu-admin.crt >> $LOG_FILE 2>&1
openssl req -new -newkey rsa:4096 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$ip:3000" -keyout /root/lamassu-server.key -out /root/lamassu-server.crt >> $LOG_FILE 2>&1
