#!/usr/bin/env bash
set -e

export LOG_FILE=/tmp/install.log
rm -f $LOG_FILE

echo -e "\nStarting \033[1mlamassu-server\033[0m install. This will take a few minutes...\n"

if [ "$(whoami)" != "root" ]; then
  echo -e "This script has to be run as \033[1mroot\033[0m user"
  exit 3
fi

export IP=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')

echo "Updating system..."
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - >> $LOG_FILE 2>&1
add-apt-repository -y ppa:bitcoin/bitcoin >> $LOG_FILE 2>&1
add-apt-repository -y ppa:ethereum/ethereum >> $LOG_FILE 2>&1
apt update >> $LOG_FILE 2>&1

echo "Installing necessary packages..."
apt install nodejs python-minimal ethereum bitcoind build-essential postgresql libpq-dev -y -q >> $LOG_FILE 2>&1

echo "Generating seed..."
SEEDS_DIR=$HOME/seeds
SEED_FILE=$SEEDS_DIR/seed.txt
mkdir -p $SEEDS_DIR >> $LOG_FILE 2>&1
SEED=$(openssl rand -hex 32)
echo $SEED > $SEED_FILE

echo "Installing lamassu-server..."
# NOTE: --unsafe-perm sounds scary but the idea of the DO box is for everything to
# run under root, since the box only does one thing. Under those assumptions,
# --unsafe-perm doesn't do anything bad.
npm install -g --unsafe-perm bunyan pm2 migrate lamassu/lamassu-server#alpha \
  lamassu/lamassu-admin#alpha lamassu/lamassu-scripts >> $LOG_FILE 2>&1

echo "Creating postgres user..."
POSTGRES_PW=$(hkdf postgres-pw $SEED)
su -l postgres >> $LOG_FILE 2>&1 <<EOF
  psql -c "CREATE ROLE lamassu_pg WITH LOGIN SUPERUSER PASSWORD '$POSTGRES_PW';"
  createdb lamassu
EOF

CERT_DIR=$HOME/certs
CONFIG_DIR=$HOME/.lamassu

mkdir -p $CERT_DIR >> $LOG_FILE 2>&1
mkdir -p $CONFIG_DIR >> $LOG_FILE 2>&1

echo "Generating SSL certificates..."
openssl req -new -newkey rsa:4096 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$IP:8081" -keyout $CERT_DIR/lamassu-admin.key  -out $CERT_DIR/lamassu-admin.crt >> $LOG_FILE 2>&1
openssl req -new -newkey rsa:4096 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$IP:3000" -keyout $CERT_DIR/lamassu-server.key -out $CERT_DIR/lamassu-server.crt >> $LOG_FILE 2>&1

cat <<EOF > $CONFIG_DIR/lamassu.json
{
  "postgresql": "postgres://lamassu_pg:$POSTGRES_PW@localhost/lamassu",
  "certPath": "$CERT_DIR/lamassu-server.crt",
  "certKeyPath": "$CERT_DIR/lamassu-server.key",
  "seedPath": "$SEED_FILE",
  "logLevel": "debug"
}
EOF

cat <<EOF > $CONFIG_DIR/lamassu-admin.json
{
  "certPath": "$CERT_DIR/lamassu-admin.crt",
  "certKeyPath": "$CERT_DIR/lamassu-admin.key"
}
EOF

NPM_ROOT=$(npm -g root)
migrate -c $NPM_ROOT/lamassu-server >> $LOG_FILE 2>&1

echo "Installing lamassu-admin..."
ADMIN_PW=$(hkdf lamassu-admin-pw $SEED)
lamassu-useradd admin $ADMIN_PW >> $LOG_FILE 2>&1

echo "Starting lamassu-admin..."
pm2 start lamassu-admin --env '{"NODE_ENV": "production"}' >> $LOG_FILE 2>&1
pm2 start lamassu-server --env '{"NODE_ENV": "production"}' --restart-delay 10000 >> $LOG_FILE 2>&1
pm2 save >> $LOG_FILE 2>&1
pm2 startup >> $LOG_FILE 2>&1

echo "Setting up backups..."
BIN=$(npm -g bin)
BACKUP_DIR=$HOME/backups/postgresql
mkdir -p $BACKUP_DIR
chown root:postgres $BACKUP_DIR >> $LOG_FILE 2>&1
chmod 664 $BACKUP_DIR >> $LOG_FILE 2>&1
BACKUP_CRON="@daily $BIN/backup-pg > /dev/null"
echo $BACKUP_CRON | crontab -u postgres - >> $LOG_FILE 2>&1
backup-pg >> $LOG_FILE 2>&1

echo "Setting up firewall..."
ufw allow ssh >> $LOG_FILE 2>&1
ufw allow 8081/tcp >> $LOG_FILE 2>&1  # Admin
ufw allow 3000/tcp >> $LOG_FILE 2>&1  # Server
ufw -f enable >> $LOG_FILE 2>&1

echo
echo "Done! Now it's time to configure Lamassu stack."
echo "Open https://$IP:8081 in your browser to access "
echo "your admin panel."
echo
echo "Default login info for lamassu-admin:"
echo "User: admin / Password: $ADMIN_PW"
echo
echo "Please write this down in a safe place."
echo -e "\n*** IMPORTANT ***"
echo "Backup the contents of $SEED_FILE in a safe place."
echo "This seed will allow you to retrieve system passwords, including "
echo "the keys to your Ethereum accounts."
echo
